/**
 * lib/mockData.ts
 * 補助金ナビAI モックデータ / DB未接続時フォールバック
 * 実際の公的補助金情報を元に作成（2024-2025年度版）
 * 国・都道府県・政令市レベルの主要制度 150件以上
 */

export const MOCK_GRANTS = [
  // ══════════════════════════════════════════════════
  // 経済産業省・中小企業庁
  // ══════════════════════════════════════════════════
  {
    id: "1",
    name: "IT導入補助金2024（通常枠）",
    ministry: "経産省",
    category: "デジタル化",
    description: "中小企業・小規模事業者のITツール導入を支援。業務効率化・売上向上を実現するソフトウェア、クラウドサービス等の導入経費を補助。補助率1/2以内、上限450万円。",
    maxAmount: 450,
    adoptionRate: 68,
    deadline: "2025/03/31",
    tags: ["IT", "業務効率化", "クラウド", "SaaS", "デジタル化"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "IT導入補助金2024（セキュリティ対策推進枠）",
    ministry: "経産省",
    category: "デジタル化",
    description: "サイバーセキュリティ対策強化のためのセキュリティソフト・サービス導入支援。補助率1/2、上限100万円。",
    maxAmount: 100,
    adoptionRate: 72,
    deadline: "2025/03/31",
    tags: ["セキュリティ", "IT", "サイバー対策"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "IT導入補助金2024（デジタル化基盤導入枠）",
    ministry: "経産省",
    category: "デジタル化",
    description: "会計・受発注・決済・ECのソフトウェア導入を支援。インボイス対応ツールも対象。補助率3/4〜4/5、上限350万円。",
    maxAmount: 350,
    adoptionRate: 74,
    deadline: "2025/03/31",
    tags: ["IT", "インボイス", "会計", "EC", "クラウド"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "ものづくり補助金（通常枠）第18回",
    ministry: "中小企業庁",
    category: "設備投資",
    description: "革新的な製品・サービス開発や生産プロセス改善のための設備投資を支援。補助率1/2（小規模2/3）、上限1,250万円。",
    maxAmount: 1250,
    adoptionRate: 47,
    deadline: "2025/01/24",
    tags: ["設備投資", "製造業", "革新", "機械装置", "DX"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "ものづくり補助金（グリーン枠）第18回",
    ministry: "中小企業庁",
    category: "設備投資",
    description: "温室効果ガス削減に向けたグリーン技術の研究開発・設備投資を支援。補助率1/2（小規模2/3）、上限4,000万円。",
    maxAmount: 4000,
    adoptionRate: 42,
    deadline: "2025/01/24",
    tags: ["グリーン", "脱炭素", "設備投資", "環境"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "ものづくり補助金（グローバル市場開拓枠）第18回",
    ministry: "中小企業庁",
    category: "設備投資",
    description: "海外市場開拓を目的とした製品・サービス開発や生産体制整備を支援。補助率1/2、上限3,000万円。",
    maxAmount: 3000,
    adoptionRate: 35,
    deadline: "2025/01/24",
    tags: ["海外展開", "輸出", "グローバル", "設備投資"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "小規模事業者持続化補助金（通常枠）第16回",
    ministry: "中小企業庁",
    category: "販路開拓",
    description: "小規模事業者の販路開拓・業務効率化を支援。チラシ・HP制作、展示会出展等の経費の2/3を補助。上限50万円。",
    maxAmount: 50,
    adoptionRate: 54,
    deadline: "2025/03/28",
    tags: ["販路拡大", "HP制作", "広告", "小規模"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "小規模事業者持続化補助金（賃金引上げ枠）第16回",
    ministry: "中小企業庁",
    category: "販路開拓",
    description: "事業場内最低賃金を地域最低賃金より+30円以上引き上げた小規模事業者が対象。上限200万円、補助率2/3。",
    maxAmount: 200,
    adoptionRate: 48,
    deadline: "2025/03/28",
    tags: ["賃上げ", "販路拡大", "小規模"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "9",
    name: "小規模事業者持続化補助金（後継者支援枠）第16回",
    ministry: "中小企業庁",
    category: "販路開拓",
    description: "アトツギ甲子園ファイナリスト等を対象とした後継者による新たな取り組みを支援。上限200万円。",
    maxAmount: 200,
    adoptionRate: 51,
    deadline: "2025/03/28",
    tags: ["事業承継", "後継者", "販路拡大"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "10",
    name: "小規模事業者持続化補助金（創業枠）第16回",
    ministry: "中小企業庁",
    category: "販路開拓",
    description: "産業競争力強化法に基づく認定市区町村での創業を行った小規模事業者が対象。上限200万円。",
    maxAmount: 200,
    adoptionRate: 46,
    deadline: "2025/03/28",
    tags: ["創業", "スタートアップ", "販路拡大"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "11",
    name: "事業再構築補助金（成長枠）第12回",
    ministry: "経産省",
    category: "事業転換",
    description: "成長分野への大胆な事業再構築に取り組む中小企業を支援。最大7,000万円。補助率1/2（中小）。",
    maxAmount: 7000,
    adoptionRate: 38,
    deadline: "2025/04/24",
    tags: ["事業転換", "成長分野", "再構築", "新事業", "DX"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "12",
    name: "事業再構築補助金（グリーン成長枠）第12回",
    ministry: "経産省",
    category: "事業転換",
    description: "グリーン成長戦略14分野の課題解決に資する事業再構築を支援。上限1億円。",
    maxAmount: 10000,
    adoptionRate: 31,
    deadline: "2025/04/24",
    tags: ["グリーン", "脱炭素", "事業転換", "環境"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "13",
    name: "事業再構築補助金（産業構造転換枠）第12回",
    ministry: "経産省",
    category: "事業転換",
    description: "国内市場縮小等の構造的課題に直面している業種・業態の事業者の事業再構築を支援。上限7,000万円。",
    maxAmount: 7000,
    adoptionRate: 35,
    deadline: "2025/04/24",
    tags: ["業種転換", "構造改革", "新事業"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "14",
    name: "事業再構築補助金（最低賃金枠）第12回",
    ministry: "経産省",
    category: "事業転換",
    description: "最低賃金近傍で雇用する従業員が相当程度いる中小企業の事業再構築を支援。補助率3/4、上限1,500万円。",
    maxAmount: 1500,
    adoptionRate: 55,
    deadline: "2025/04/24",
    tags: ["最低賃金", "雇用", "事業転換"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "15",
    name: "事業承継・引継ぎ補助金（経営革新枠）",
    ministry: "中小企業庁",
    category: "事業承継",
    description: "事業承継・M&Aを契機として経営革新等に取り組む中小企業を支援。上限600万円、補助率2/3。",
    maxAmount: 600,
    adoptionRate: 58,
    deadline: "2025/05/31",
    tags: ["事業承継", "M&A", "経営革新", "後継者"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "16",
    name: "事業承継・引継ぎ補助金（専門家活用枠）",
    ministry: "中小企業庁",
    category: "事業承継",
    description: "M&A成立に向けた専門家（FA・仲介）活用費用を補助。上限600万円、補助率2/3。",
    maxAmount: 600,
    adoptionRate: 62,
    deadline: "2025/05/31",
    tags: ["M&A", "専門家", "事業承継"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "17",
    name: "中小企業省力化投資補助金",
    ministry: "中小企業庁",
    category: "デジタル化",
    description: "人手不足に悩む中小企業の省力化投資を支援。IoT・ロボット等のカタログ掲載製品導入費用を補助。上限1,500万円。",
    maxAmount: 1500,
    adoptionRate: 65,
    deadline: "2025/06/30",
    tags: ["省力化", "ロボット", "IoT", "人手不足", "自動化"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "18",
    name: "JAPANブランド育成支援等事業",
    ministry: "中小企業庁",
    category: "海外展開",
    description: "日本の中小企業が海外で通用するブランド力を磨く取り組みを支援。上限500万円。",
    maxAmount: 500,
    adoptionRate: 43,
    deadline: "2025/04/30",
    tags: ["海外展開", "ブランド", "輸出", "マーケティング"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "19",
    name: "新事業進出補助金（新市場展開型）",
    ministry: "中小企業庁",
    category: "事業転換",
    description: "中小企業・小規模事業者が自社の経営資源を活用して新市場開拓を行う取り組みを支援。上限3,000万円。",
    maxAmount: 3000,
    adoptionRate: 40,
    deadline: "2025/06/30",
    tags: ["新事業", "市場開拓", "成長", "DX"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "20",
    name: "サプライチェーン対策のための国内投資促進補助金",
    ministry: "経産省",
    category: "設備投資",
    description: "特定重要物資の生産基盤整備や供給確保のための設備投資を支援。大型補助で最大数十億円規模も対象。",
    maxAmount: 15000,
    adoptionRate: 28,
    deadline: "2025/03/31",
    tags: ["サプライチェーン", "国内回帰", "設備投資", "重要物資"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "21",
    name: "地域未来投資促進補助金",
    ministry: "経産省",
    category: "地域活性化",
    description: "地域の特性を活かした高い付加価値を創出する事業を支援。地域経済牽引事業計画の認定が要件。上限5,000万円。",
    maxAmount: 5000,
    adoptionRate: 40,
    deadline: "2025/05/30",
    tags: ["地域活性化", "付加価値", "地方", "連携"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "22",
    name: "中小企業EC活用支援補助金（小規模持続化特例）",
    ministry: "中小企業庁",
    category: "販路開拓",
    description: "ネット通販サイト構築・ECプラットフォーム活用による販路拡大を支援。HP制作・EC導入費の2/3補助。上限100万円。",
    maxAmount: 100,
    adoptionRate: 65,
    deadline: "2025/03/28",
    tags: ["EC", "ネット通販", "HP制作", "販路拡大"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 厚生労働省（雇用・人材）
  // ══════════════════════════════════════════════════
  {
    id: "23",
    name: "キャリアアップ助成金（正社員化コース）",
    ministry: "厚労省",
    category: "人材育成",
    description: "有期雇用労働者等を正規雇用等に転換した場合に助成。1人当たり最大80万円。通年受付。",
    maxAmount: 96,
    adoptionRate: 81,
    deadline: "通年",
    tags: ["正社員化", "非正規", "雇用転換", "処遇改善"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "24",
    name: "キャリアアップ助成金（賃金規定等改定コース）",
    ministry: "厚労省",
    category: "人材育成",
    description: "有期雇用労働者等の賃金規定等を改定し3%以上賃金増額した場合に助成。1人最大5万円。",
    maxAmount: 50,
    adoptionRate: 78,
    deadline: "通年",
    tags: ["賃上げ", "非正規", "賃金改定"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "25",
    name: "キャリアアップ助成金（社会保険適用時処遇改善コース）",
    ministry: "厚労省",
    category: "人材育成",
    description: "短時間労働者が新たに社会保険を適用される際、手取り収入が減らないよう取り組む事業主に助成。最大50万円。",
    maxAmount: 50,
    adoptionRate: 73,
    deadline: "通年",
    tags: ["社会保険", "パート", "処遇改善"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "26",
    name: "業務改善助成金",
    ministry: "厚労省",
    category: "設備投資",
    description: "事業場内最低賃金を一定額以上引き上げ、生産性向上のための設備投資等を行った場合に助成。上限600万円。",
    maxAmount: 600,
    adoptionRate: 74,
    deadline: "2025/01/31",
    tags: ["賃上げ", "最低賃金", "設備投資", "生産性向上"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "27",
    name: "人材開発支援助成金（人材育成支援コース）",
    ministry: "厚労省",
    category: "人材育成",
    description: "労働者のスキルアップのための訓練を実施した事業主への助成。訓練経費・訓練中の賃金の一部を助成。通年受付。",
    maxAmount: 200,
    adoptionRate: 77,
    deadline: "通年",
    tags: ["研修", "訓練", "スキルアップ", "OJT"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "28",
    name: "人材開発支援助成金（教育訓練休暇等付与コース）",
    ministry: "厚労省",
    category: "人材育成",
    description: "雇用する労働者に有給教育訓練休暇制度等を導入・実施した場合に助成。最大150万円。",
    maxAmount: 150,
    adoptionRate: 69,
    deadline: "通年",
    tags: ["教育訓練", "休暇制度", "スキルアップ"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "29",
    name: "人材開発支援助成金（事業展開等リスキリング支援コース）",
    ministry: "厚労省",
    category: "人材育成",
    description: "デジタル化・事業転換に対応するためのリスキリング（学び直し）訓練を支援。補助率最大75%。",
    maxAmount: 300,
    adoptionRate: 71,
    deadline: "通年",
    tags: ["リスキリング", "DX", "デジタル", "研修"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "30",
    name: "働き方改革推進支援助成金（労働時間短縮・年休促進支援コース）",
    ministry: "厚労省",
    category: "人材育成",
    description: "労働時間の短縮や年次有給休暇の促進に取り組む中小企業を支援。設備投資等に最大250万円。",
    maxAmount: 250,
    adoptionRate: 71,
    deadline: "2025/02/28",
    tags: ["働き方改革", "残業削減", "有給休暇"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "31",
    name: "働き方改革推進支援助成金（勤務間インターバル導入コース）",
    ministry: "厚労省",
    category: "人材育成",
    description: "勤務間インターバル制度の導入に取り組む中小企業に助成。最大100万円。",
    maxAmount: 100,
    adoptionRate: 68,
    deadline: "2025/02/28",
    tags: ["働き方改革", "インターバル", "労働時間"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "32",
    name: "両立支援等助成金（出生時両立支援コース）",
    ministry: "厚労省",
    category: "人材育成",
    description: "男性労働者の育児休業取得を支援する雇用環境整備に取り組んだ場合に助成。最大57万円。",
    maxAmount: 57,
    adoptionRate: 76,
    deadline: "通年",
    tags: ["育休", "男性育休", "両立支援"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "33",
    name: "両立支援等助成金（介護離職防止支援コース）",
    ministry: "厚労省",
    category: "人材育成",
    description: "介護を抱える労働者の離職防止のための職場環境整備に取り組む事業主に助成。最大125万円。",
    maxAmount: 125,
    adoptionRate: 70,
    deadline: "通年",
    tags: ["介護離職防止", "両立支援", "職場環境"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "34",
    name: "雇用調整助成金",
    ministry: "厚労省",
    category: "雇用",
    description: "経済上の理由で事業活動が縮小した際に休業・教育訓練・出向で雇用維持した事業主を助成。",
    maxAmount: 900,
    adoptionRate: 72,
    deadline: "通年",
    tags: ["雇用維持", "休業", "経済対策"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "35",
    name: "トライアル雇用助成金（一般トライアルコース）",
    ministry: "厚労省",
    category: "雇用",
    description: "就職困難な求職者をトライアル雇用した事業主に助成。1人月最大4万円×3か月。",
    maxAmount: 36,
    adoptionRate: 83,
    deadline: "通年",
    tags: ["採用", "トライアル雇用", "就職困難者"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "36",
    name: "特定求職者雇用開発助成金（特定就職困難者コース）",
    ministry: "厚労省",
    category: "雇用",
    description: "高齢者や障害者等の就職困難者をハローワーク等の紹介で雇用した事業主に助成。最大240万円。",
    maxAmount: 240,
    adoptionRate: 80,
    deadline: "通年",
    tags: ["高齢者雇用", "障害者雇用", "雇用促進"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "37",
    name: "特定求職者雇用開発助成金（成長分野等人材確保・育成コース）",
    ministry: "厚労省",
    category: "雇用",
    description: "デジタル・グリーン等の成長分野で就職支援を受けた求職者を雇い入れた事業主に助成。最大240万円。",
    maxAmount: 240,
    adoptionRate: 75,
    deadline: "通年",
    tags: ["DX人材", "グリーン", "採用", "雇用促進"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "38",
    name: "障害者雇用安定助成金（障害者職場適応援助コース）",
    ministry: "厚労省",
    category: "雇用",
    description: "障害者の職場定着に向けた職場適応援助者（ジョブコーチ）の支援に助成。最大280万円。",
    maxAmount: 280,
    adoptionRate: 79,
    deadline: "通年",
    tags: ["障害者雇用", "ジョブコーチ", "職場定着"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 環境省
  // ══════════════════════════════════════════════════
  {
    id: "39",
    name: "省エネルギー投資促進支援事業費補助金（設備単位）",
    ministry: "環境省",
    category: "省エネ",
    description: "省エネルギー設備への更新を支援。エネルギー管理システムや高効率設備導入費用の1/3〜1/2を補助。上限3,000万円。",
    maxAmount: 3000,
    adoptionRate: 62,
    deadline: "2025/02/28",
    tags: ["省エネ", "CO2削減", "設備投資", "エネルギー"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "40",
    name: "二酸化炭素排出抑制対策事業費等補助金（再エネ）",
    ministry: "環境省",
    category: "省エネ",
    description: "再生可能エネルギー設備の導入（太陽光・蓄電池等）を支援。脱炭素化に取り組む中小企業が対象。",
    maxAmount: 2000,
    adoptionRate: 55,
    deadline: "2025/03/31",
    tags: ["再エネ", "太陽光", "脱炭素", "蓄電池"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "41",
    name: "脱炭素社会構築に向けた再エネ等由来水素活用推進事業",
    ministry: "環境省",
    category: "省エネ",
    description: "水素・燃料電池等の導入による脱炭素化を支援。水素関連設備導入費の補助。上限5,000万円。",
    maxAmount: 5000,
    adoptionRate: 30,
    deadline: "2025/04/30",
    tags: ["水素", "燃料電池", "脱炭素", "グリーン"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "42",
    name: "飲食店・宿泊業等省エネ設備導入補助金",
    ministry: "環境省",
    category: "省エネ",
    description: "飲食店・宿泊施設等のCO2排出量削減に向けた省エネ設備（冷蔵庫・空調等）の更新を支援。上限100万円。",
    maxAmount: 100,
    adoptionRate: 70,
    deadline: "2025/09/30",
    tags: ["飲食", "宿泊", "省エネ", "設備更新"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "43",
    name: "地域脱炭素移行・再エネ推進交付金",
    ministry: "環境省",
    category: "省エネ",
    description: "脱炭素先行地域の計画実現のための設備導入・インフラ整備を支援。地方公共団体が応募主体。",
    maxAmount: 30000,
    adoptionRate: 35,
    deadline: "2025/06/30",
    tags: ["脱炭素", "再エネ", "地域", "インフラ"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 国土交通省
  // ══════════════════════════════════════════════════
  {
    id: "44",
    name: "建設業DX助成金",
    ministry: "国交省",
    category: "デジタル化",
    description: "建設業のDX推進（BIM/CIM、ICT施工等）のためのソフトウェア・機器導入を支援。上限300万円。",
    maxAmount: 300,
    adoptionRate: 58,
    deadline: "2025/05/31",
    tags: ["建設業", "DX", "BIM", "ICT"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "45",
    name: "物流効率化・低炭素化推進事業補助金",
    ministry: "国交省",
    category: "設備投資",
    description: "トラック輸送の省エネ化や共同配送等の物流効率化に取り組む事業者を支援。EVトラック等の導入補助。上限1,000万円。",
    maxAmount: 1000,
    adoptionRate: 49,
    deadline: "2025/03/31",
    tags: ["物流", "EV", "省エネ", "共同配送"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "46",
    name: "住宅・建築物省エネ改修等推進事業（先進的窓リノベ）",
    ministry: "国交省",
    category: "省エネ",
    description: "既存住宅・建築物の断熱改修（窓・外壁等）を支援。補助率1/3〜1/2、上限200万円。",
    maxAmount: 200,
    adoptionRate: 67,
    deadline: "2025/12/31",
    tags: ["リノベーション", "断熱", "省エネ", "住宅"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "47",
    name: "建設現場のICT活用推進補助金",
    ministry: "国交省",
    category: "デジタル化",
    description: "建設現場でのドローン測量・ICT施工・BIM/CIM活用のための機器・ソフトウェア導入を支援。上限500万円。",
    maxAmount: 500,
    adoptionRate: 54,
    deadline: "2025/06/30",
    tags: ["建設", "ドローン", "ICT施工", "BIM"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "48",
    name: "観光地域づくり法人（DMO）形成・確立支援事業",
    ministry: "観光庁",
    category: "観光",
    description: "地域の観光資源の磨き上げや誘客促進のための取り組みを支援。デジタルマーケティング活用も対象。上限800万円。",
    maxAmount: 800,
    adoptionRate: 42,
    deadline: "2025/10/31",
    tags: ["観光", "DMO", "インバウンド", "地域活性化"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 農林水産省
  // ══════════════════════════════════════════════════
  {
    id: "49",
    name: "農業経営基盤強化支援補助金",
    ministry: "農水省",
    category: "農業",
    description: "農業経営の基盤強化のためのスマート農業機械・設備等の導入を支援。経営効率化・省力化に取り組む農業者が対象。上限1,500万円。",
    maxAmount: 1500,
    adoptionRate: 45,
    deadline: "2025/06/30",
    tags: ["農業", "スマート農業", "設備投資", "省力化"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "50",
    name: "みどりの食料システム戦略推進交付金",
    ministry: "農水省",
    category: "農業",
    description: "有機農業や農薬・化学肥料低減等の環境負荷低減に取り組む農業者・団体を支援。上限2,000万円。",
    maxAmount: 2000,
    adoptionRate: 50,
    deadline: "2025/04/30",
    tags: ["有機農業", "環境", "農業", "持続可能"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "51",
    name: "農山漁村振興交付金（農泊推進）",
    ministry: "農水省",
    category: "農業",
    description: "農山漁村における農泊の推進のための施設整備・ICT活用等を支援。インバウンド誘致にも活用可能。上限500万円。",
    maxAmount: 500,
    adoptionRate: 48,
    deadline: "2025/05/31",
    tags: ["農泊", "観光", "農山漁村", "インバウンド"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "52",
    name: "食料産業・6次産業化交付金",
    ministry: "農水省",
    category: "農業",
    description: "農業者等が行う農林水産物の加工・販売等の6次産業化や農商工連携の取り組みを支援。上限1,000万円。",
    maxAmount: 1000,
    adoptionRate: 47,
    deadline: "2025/05/31",
    tags: ["6次産業化", "農業", "加工", "販売"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "53",
    name: "強い農業・担い手づくり総合支援交付金",
    ministry: "農水省",
    category: "農業",
    description: "農業用機械・施設等の導入を支援する融資主体型補助事業。機械・施設導入費の1/2等を補助。",
    maxAmount: 5000,
    adoptionRate: 44,
    deadline: "2025/04/30",
    tags: ["農業機械", "担い手", "スマート農業", "施設"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 総務省・デジタル庁
  // ══════════════════════════════════════════════════
  {
    id: "54",
    name: "地域IoT実装推進交付金",
    ministry: "総務省",
    category: "デジタル化",
    description: "地域が直面する課題解決のためのIoT・AI・ビッグデータ活用を支援。地方公共団体との連携が要件。上限500万円。",
    maxAmount: 500,
    adoptionRate: 38,
    deadline: "2025/06/30",
    tags: ["IoT", "AI", "ビッグデータ", "地域課題", "DX"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "55",
    name: "デジタル田園都市国家構想交付金（DXタイプ）",
    ministry: "デジタル庁",
    category: "デジタル化",
    description: "地方のデジタル実装による地域課題解決を支援。地方公共団体・民間の連携プロジェクトに補助。上限1,000万円。",
    maxAmount: 1000,
    adoptionRate: 42,
    deadline: "2025/05/31",
    tags: ["DX", "デジタル化", "地域活性化", "スマートシティ"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "56",
    name: "地域情報化アドバイザー派遣制度",
    ministry: "総務省",
    category: "デジタル化",
    description: "地域の情報化・DX推進のための専門家派遣制度。費用は公費負担（実質無料）。",
    maxAmount: 0,
    adoptionRate: 85,
    deadline: "通年",
    tags: ["DX", "専門家派遣", "情報化", "地域"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 医療・介護
  // ══════════════════════════════════════════════════
  {
    id: "57",
    name: "介護ロボット導入支援事業補助金",
    ministry: "厚労省",
    category: "設備投資",
    description: "介護事業所における介護ロボット・ICT機器の導入費用を補助。移乗支援ロボット等も対象。上限300万円。",
    maxAmount: 300,
    adoptionRate: 73,
    deadline: "2025/11/30",
    tags: ["介護", "ロボット", "ICT", "省力化"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "58",
    name: "医療機関等における感染防止対策補助金",
    ministry: "厚労省",
    category: "設備投資",
    description: "医療機関・介護施設等の感染防止対策強化のための設備・備品整備を支援。空気清浄機・換気設備等が対象。上限200万円。",
    maxAmount: 200,
    adoptionRate: 78,
    deadline: "2025/03/31",
    tags: ["医療", "介護", "感染対策", "設備"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "59",
    name: "介護施設ICT導入支援補助金",
    ministry: "厚労省",
    category: "デジタル化",
    description: "介護施設における介護記録ソフト・センサー等のICT機器導入費用を補助。業務効率化・人材不足解消が目的。上限260万円。",
    maxAmount: 260,
    adoptionRate: 76,
    deadline: "通年",
    tags: ["介護", "ICT", "デジタル化", "記録システム"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 東京都
  // ══════════════════════════════════════════════════
  {
    id: "60",
    name: "東京都 中小企業設備投資補助金",
    ministry: "東京都",
    category: "設備投資",
    description: "都内中小企業の競争力強化のための設備投資を支援。補助率1/2、上限500万円。",
    maxAmount: 500,
    adoptionRate: 55,
    deadline: "2025/07/15",
    tags: ["東京", "設備投資", "競争力強化"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "61",
    name: "東京都 デジタル基盤整備助成事業",
    ministry: "東京都",
    category: "デジタル化",
    description: "中小企業のデジタル化推進のためのITシステム・ソフトウェア導入を支援。補助率2/3、上限750万円。",
    maxAmount: 750,
    adoptionRate: 60,
    deadline: "2025/06/30",
    tags: ["東京", "DX", "デジタル化", "IT"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "62",
    name: "東京都 躍進的な事業推進のための設備投資支援事業",
    ministry: "東京都",
    category: "設備投資",
    description: "IoT・AI・ロボット等の先端設備や製品製造設備の導入を支援。上限1億5,000万円の大型補助。",
    maxAmount: 15000,
    adoptionRate: 38,
    deadline: "2025/05/31",
    tags: ["東京", "IoT", "AI", "ロボット", "大型設備"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "63",
    name: "東京都 創業助成金",
    ministry: "東京都",
    category: "創業",
    description: "東京都内での創業を促進するため、創業初期費用（賃借料・設備費・広告費等）を助成。上限300万円。",
    maxAmount: 300,
    adoptionRate: 44,
    deadline: "2025/04/30",
    tags: ["東京", "創業", "スタートアップ", "起業"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "64",
    name: "東京都 多摩地域中小企業振興助成金",
    ministry: "東京都",
    category: "設備投資",
    description: "多摩地域の中小企業の技術力強化・市場開拓を支援。設備投資・販路開拓等が対象。上限400万円。",
    maxAmount: 400,
    adoptionRate: 52,
    deadline: "2025/07/31",
    tags: ["東京", "多摩", "設備投資", "中小企業"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "65",
    name: "東京都 省エネ・再エネ導入助成金",
    ministry: "東京都",
    category: "省エネ",
    description: "都内中小企業の省エネルギー設備・再生可能エネルギー設備の導入費用を助成。上限2,000万円。",
    maxAmount: 2000,
    adoptionRate: 57,
    deadline: "2025/08/31",
    tags: ["東京", "省エネ", "再エネ", "太陽光"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 大阪府・大阪市
  // ══════════════════════════════════════════════════
  {
    id: "66",
    name: "大阪府 中小企業技術開発支援補助金",
    ministry: "大阪府",
    category: "技術開発",
    description: "大阪府内中小企業の新技術・新製品開発を支援。研究開発費等の2/3を補助、上限500万円。",
    maxAmount: 500,
    adoptionRate: 52,
    deadline: "2025/06/30",
    tags: ["大阪", "技術開発", "R&D", "新製品"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "67",
    name: "大阪市 スタートアップ成長支援事業",
    ministry: "大阪市",
    category: "創業",
    description: "大阪市内の起業家・スタートアップの成長を支援。事業化・販路開拓費用の一部を補助。上限200万円。",
    maxAmount: 200,
    adoptionRate: 46,
    deadline: "2025/05/31",
    tags: ["大阪", "スタートアップ", "起業", "創業"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "68",
    name: "大阪府 スマートものづくり補助金",
    ministry: "大阪府",
    category: "設備投資",
    description: "IoT・AI等を活用したスマートものづくりに取り組む中小製造業を支援。設備投資費の1/2補助。上限1,000万円。",
    maxAmount: 1000,
    adoptionRate: 49,
    deadline: "2025/07/31",
    tags: ["大阪", "製造業", "IoT", "AI", "スマート工場"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 愛知県・名古屋市
  // ══════════════════════════════════════════════════
  {
    id: "69",
    name: "愛知県 あいち産業振興機構 中小企業支援補助金",
    ministry: "愛知県",
    category: "設備投資",
    description: "愛知県内の中小企業の設備投資・技術開発・販路開拓を支援。補助率1/2、上限300万円。",
    maxAmount: 300,
    adoptionRate: 57,
    deadline: "2025/07/31",
    tags: ["愛知", "設備投資", "製造業", "技術開発"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "70",
    name: "名古屋市 産業DX促進補助金",
    ministry: "名古屋市",
    category: "デジタル化",
    description: "名古屋市内の中小企業・個人事業主のDX推進を支援。ITシステム・ソフトウェア導入費の2/3を補助。上限50万円。",
    maxAmount: 50,
    adoptionRate: 65,
    deadline: "2025/09/30",
    tags: ["名古屋", "DX", "デジタル化", "IT"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 神奈川県・横浜市・川崎市
  // ══════════════════════════════════════════════════
  {
    id: "71",
    name: "神奈川県 中小企業DX化支援補助金",
    ministry: "神奈川県",
    category: "デジタル化",
    description: "神奈川県内の中小企業のDX推進を支援。業務管理システム・EC構築等のITツール導入費を補助。上限100万円。",
    maxAmount: 100,
    adoptionRate: 63,
    deadline: "2025/08/31",
    tags: ["神奈川", "DX", "デジタル化"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "72",
    name: "横浜市 中小企業ビジネス化補助金",
    ministry: "横浜市",
    category: "技術開発",
    description: "横浜市内の中小企業の新製品開発・新事業化等の取り組みを支援。上限300万円、補助率1/2。",
    maxAmount: 300,
    adoptionRate: 54,
    deadline: "2025/06/30",
    tags: ["横浜", "新製品", "技術開発", "新事業"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "73",
    name: "川崎市 臨海部立地補助金",
    ministry: "川崎市",
    category: "設備投資",
    description: "川崎市臨海部への事業立地・設備投資を行う企業に対して補助。製造業・研究開発施設が対象。上限5,000万円。",
    maxAmount: 5000,
    adoptionRate: 38,
    deadline: "2025/08/31",
    tags: ["川崎", "設備投資", "製造業", "立地"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 埼玉県・千葉県・茨城県
  // ══════════════════════════════════════════════════
  {
    id: "74",
    name: "埼玉県 ものづくり企業新事業展開支援補助金",
    ministry: "埼玉県",
    category: "設備投資",
    description: "埼玉県内の製造業が新製品開発・新事業展開に取り組む際の費用を支援。上限500万円、補助率1/2。",
    maxAmount: 500,
    adoptionRate: 53,
    deadline: "2025/06/30",
    tags: ["埼玉", "製造業", "新事業", "設備投資"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "75",
    name: "千葉県 中小企業振興基金助成金（新事業展開支援）",
    ministry: "千葉県",
    category: "技術開発",
    description: "千葉県内の中小企業の新製品・新技術開発や新分野進出を支援。試作品製作費等を補助。上限200万円。",
    maxAmount: 200,
    adoptionRate: 56,
    deadline: "2025/07/31",
    tags: ["千葉", "新事業", "技術開発", "試作品"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "76",
    name: "茨城県 いばらき産業大県創生補助金",
    ministry: "茨城県",
    category: "設備投資",
    description: "茨城県内に立地する中小企業等の設備投資・技術開発・創業等を支援。上限1,000万円。",
    maxAmount: 1000,
    adoptionRate: 51,
    deadline: "2025/08/31",
    tags: ["茨城", "設備投資", "創業", "技術開発"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 福岡県・福岡市
  // ══════════════════════════════════════════════════
  {
    id: "77",
    name: "福岡県 中小企業振興補助金",
    ministry: "福岡県",
    category: "設備投資",
    description: "福岡県内の中小企業の経営力強化のための設備投資・人材育成・販路開拓等を支援。上限300万円。",
    maxAmount: 300,
    adoptionRate: 56,
    deadline: "2025/07/31",
    tags: ["福岡", "中小企業", "設備投資"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "78",
    name: "福岡スタートアップ総合支援プログラム",
    ministry: "福岡市",
    category: "創業",
    description: "福岡市内での創業・スタートアップ支援。スタートアップビザ取得支援も含む。起業費用最大100万円補助。",
    maxAmount: 100,
    adoptionRate: 42,
    deadline: "2025/09/30",
    tags: ["福岡", "スタートアップ", "創業", "起業"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "79",
    name: "福岡県 グローバルビジネス展開支援補助金",
    ministry: "福岡県",
    category: "海外展開",
    description: "福岡県内中小企業の海外市場開拓のための展示会出展・WEBサイト多言語化・翻訳等を支援。上限100万円。",
    maxAmount: 100,
    adoptionRate: 60,
    deadline: "2025/08/31",
    tags: ["福岡", "海外展開", "輸出", "多言語化"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 北海道・東北
  // ══════════════════════════════════════════════════
  {
    id: "80",
    name: "北海道 中小企業総合振興資金（補助金）",
    ministry: "北海道",
    category: "設備投資",
    description: "北海道内の中小企業の設備投資・技術開発等を支援。地域特性を活かした事業展開を促進。上限500万円。",
    maxAmount: 500,
    adoptionRate: 50,
    deadline: "2025/08/31",
    tags: ["北海道", "設備投資", "地域"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "81",
    name: "宮城県 みやぎの仕事環境整備補助金",
    ministry: "宮城県",
    category: "人材育成",
    description: "宮城県内の事業者が職場環境改善・人材確保に取り組む費用を補助。テレワーク整備等も対象。上限100万円。",
    maxAmount: 100,
    adoptionRate: 61,
    deadline: "2025/06/30",
    tags: ["宮城", "働き方改革", "テレワーク"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "82",
    name: "岩手県 いわて産業振興センター 新事業創出支援補助金",
    ministry: "岩手県",
    category: "技術開発",
    description: "岩手県内の中小企業の新製品・新技術開発、創業等を支援。上限200万円、補助率1/2。",
    maxAmount: 200,
    adoptionRate: 52,
    deadline: "2025/07/31",
    tags: ["岩手", "新事業", "技術開発", "創業"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "83",
    name: "仙台市 中小企業DX推進補助金",
    ministry: "仙台市",
    category: "デジタル化",
    description: "仙台市内の中小企業のDX推進のためのITシステム・ソフトウェア導入費用を補助。上限50万円。",
    maxAmount: 50,
    adoptionRate: 66,
    deadline: "2025/09/30",
    tags: ["仙台", "DX", "デジタル化", "IT"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 中部・北陸
  // ══════════════════════════════════════════════════
  {
    id: "84",
    name: "静岡県 新産業集積クラスター事業補助金",
    ministry: "静岡県",
    category: "技術開発",
    description: "静岡県内の新産業集積クラスター形成に向けた企業の研究開発・設備投資等を支援。上限500万円。",
    maxAmount: 500,
    adoptionRate: 48,
    deadline: "2025/06/30",
    tags: ["静岡", "クラスター", "研究開発", "製造業"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "85",
    name: "新潟県 にいがた産業創造機構（NICO）補助金",
    ministry: "新潟県",
    category: "販路開拓",
    description: "新潟県内の中小企業の販路開拓・海外展開・新商品開発等を支援。上限300万円。",
    maxAmount: 300,
    adoptionRate: 55,
    deadline: "2025/07/31",
    tags: ["新潟", "販路開拓", "海外展開", "新商品"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "86",
    name: "石川県 いしかわ中小企業チャレンジ支援ファンド",
    ministry: "石川県",
    category: "技術開発",
    description: "石川県内の中小企業の創業・新事業展開・技術開発等に対するファンドからの補助。上限500万円。",
    maxAmount: 500,
    adoptionRate: 50,
    deadline: "2025/06/30",
    tags: ["石川", "創業", "新事業", "技術開発"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "87",
    name: "長野県 産業技術総合センター 共同研究補助金",
    ministry: "長野県",
    category: "技術開発",
    description: "長野県内の中小企業と産業技術総合センターとの共同研究・技術開発を支援。上限200万円。",
    maxAmount: 200,
    adoptionRate: 53,
    deadline: "2025/05/31",
    tags: ["長野", "共同研究", "技術開発"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 近畿（京都・兵庫・奈良・滋賀）
  // ══════════════════════════════════════════════════
  {
    id: "88",
    name: "京都府 京もの産地振興補助金",
    ministry: "京都府",
    category: "販路開拓",
    description: "京都の伝統産業・地場産業の振興のための設備導入・販路開拓・人材育成等を支援。上限300万円。",
    maxAmount: 300,
    adoptionRate: 58,
    deadline: "2025/06/30",
    tags: ["京都", "伝統産業", "販路拡大", "地場産業"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "89",
    name: "神戸市 次世代産業創造補助金",
    ministry: "神戸市",
    category: "技術開発",
    description: "神戸市内のスタートアップ・中小企業の革新的な製品・サービス開発を支援。上限500万円。",
    maxAmount: 500,
    adoptionRate: 45,
    deadline: "2025/07/31",
    tags: ["神戸", "スタートアップ", "技術開発", "イノベーション"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "90",
    name: "兵庫県 産業立地促進補助金（工場等設備投資）",
    ministry: "兵庫県",
    category: "設備投資",
    description: "兵庫県内への工場・事業所立地や設備投資を行う企業に対して補助。雇用創出も加点対象。上限5,000万円。",
    maxAmount: 5000,
    adoptionRate: 40,
    deadline: "2025/09/30",
    tags: ["兵庫", "設備投資", "工場", "立地"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 中国・四国
  // ══════════════════════════════════════════════════
  {
    id: "91",
    name: "広島県 ひろしまサンドボックス事業",
    ministry: "広島県",
    category: "デジタル化",
    description: "AIやIoT等の最先端技術を活用した革新的な実証実験を支援。新技術の社会実装を促進。上限1,000万円。",
    maxAmount: 1000,
    adoptionRate: 36,
    deadline: "2025/05/31",
    tags: ["広島", "AI", "IoT", "実証実験", "DX"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "92",
    name: "岡山県 中小企業新事業応援ファンド",
    ministry: "岡山県",
    category: "技術開発",
    description: "岡山県内の中小企業の新製品開発・新事業展開を支援するファンドからの補助。上限200万円。",
    maxAmount: 200,
    adoptionRate: 54,
    deadline: "2025/06/30",
    tags: ["岡山", "新事業", "新製品", "技術開発"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "93",
    name: "愛媛県 えひめ産業振興財団 中小企業技術高度化補助金",
    ministry: "愛媛県",
    category: "技術開発",
    description: "愛媛県内の中小企業の技術高度化・新製品開発のための研究開発費を補助。上限300万円。",
    maxAmount: 300,
    adoptionRate: 51,
    deadline: "2025/07/31",
    tags: ["愛媛", "技術開発", "新製品", "研究開発"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 九州・沖縄
  // ══════════════════════════════════════════════════
  {
    id: "94",
    name: "沖縄型産業振興プロジェクト支援事業",
    ministry: "沖縄県",
    category: "地域活性化",
    description: "沖縄の地域特性を活かした産業振興・観光・IT等の事業展開を支援。離島企業も対象。上限500万円。",
    maxAmount: 500,
    adoptionRate: 47,
    deadline: "2025/07/31",
    tags: ["沖縄", "観光", "IT", "地域産業"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "95",
    name: "熊本県 半導体・蓄電池関連企業立地促進補助金",
    ministry: "熊本県",
    category: "設備投資",
    description: "熊本県内への半導体・蓄電池関連企業の立地・設備投資を促進。TSMC関連サプライヤー等が対象。上限10億円。",
    maxAmount: 100000,
    adoptionRate: 35,
    deadline: "2025/09/30",
    tags: ["熊本", "半導体", "TSMC", "設備投資", "立地"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "96",
    name: "鹿児島県 かごしま産業支援センター 経営革新支援補助金",
    ministry: "鹿児島県",
    category: "技術開発",
    description: "鹿児島県内の中小企業の経営革新計画に基づく新製品開発・新事業展開等を支援。上限200万円。",
    maxAmount: 200,
    adoptionRate: 55,
    deadline: "2025/07/31",
    tags: ["鹿児島", "経営革新", "新製品", "新事業"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 文部科学省・NEDO・JST
  // ══════════════════════════════════════════════════
  {
    id: "97",
    name: "NEDO 先導研究プログラム",
    ministry: "NEDO",
    category: "技術開発",
    description: "次世代産業の基盤となる先導的な研究開発を支援。中小企業・スタートアップも応募可能。上限5,000万円。",
    maxAmount: 5000,
    adoptionRate: 25,
    deadline: "2025/05/31",
    tags: ["研究開発", "NEDO", "先端技術", "スタートアップ"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "98",
    name: "JST START（大学発スタートアップ創出）",
    ministry: "JST",
    category: "創業",
    description: "大学等の研究成果を活用したスタートアップの事業化を支援。POC支援から本格起業まで最大3,000万円。",
    maxAmount: 3000,
    adoptionRate: 30,
    deadline: "2025/06/30",
    tags: ["スタートアップ", "大学発", "研究開発", "ディープテック"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "99",
    name: "SBIR（中小企業技術革新研究開発制度）",
    ministry: "経産省",
    category: "技術開発",
    description: "政府調達ニーズに応える中小企業の技術研究開発を支援。フェーズ1（FS）最大130万円、フェーズ2（R&D）最大3,000万円。",
    maxAmount: 3000,
    adoptionRate: 32,
    deadline: "2025/04/30",
    tags: ["研究開発", "政府調達", "中小企業", "イノベーション"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 内閣府・復興庁
  // ══════════════════════════════════════════════════
  {
    id: "100",
    name: "地方創生推進交付金（地方版成長戦略）",
    ministry: "内閣府",
    category: "地域活性化",
    description: "地方の自主的・主体的な地方創生に向けた取り組みを支援。地方公共団体が応募主体。上限1,000万円。",
    maxAmount: 1000,
    adoptionRate: 38,
    deadline: "2025/05/31",
    tags: ["地方創生", "地域活性化", "まちづくり"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "101",
    name: "東日本大震災復興特別補助金",
    ministry: "復興庁",
    category: "地域活性化",
    description: "東日本大震災の被災地（岩手・宮城・福島）における事業再建・新事業展開を支援。上限1,000万円。",
    maxAmount: 1000,
    adoptionRate: 58,
    deadline: "2025/06/30",
    tags: ["復興", "東北", "被災地", "新事業"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 金融庁・財務省系
  // ══════════════════════════════════════════════════
  {
    id: "102",
    name: "日本政策金融公庫 新規開業資金（創業融資）",
    ministry: "日本公庫",
    category: "創業",
    description: "新たに事業を始める方や事業開始後おおむね7年以内の方向けの融資制度。融資上限7,200万円、実質無担保・無保証も可能（補助金ではなく融資）。",
    maxAmount: 7200,
    adoptionRate: 78,
    deadline: "通年",
    tags: ["創業融資", "スタートアップ", "起業", "無担保"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "103",
    name: "信用保証協会 創業保証",
    ministry: "中小企業庁",
    category: "創業",
    description: "創業時の融資に対する信用保証。保証割合100%で銀行借入を支援。保証限度額3,500万円（無担保）。",
    maxAmount: 3500,
    adoptionRate: 80,
    deadline: "通年",
    tags: ["創業融資", "信用保証", "銀行借入"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════════
  // 特定業種・特定目的
  // ══════════════════════════════════════════════════
  {
    id: "104",
    name: "自動車部品メーカー カーボンニュートラル対応補助金",
    ministry: "経産省",
    category: "省エネ",
    description: "自動車部品メーカーのEV・HV対応と脱炭素化のための設備投資・研究開発を支援。上限5,000万円。",
    maxAmount: 5000,
    adoptionRate: 40,
    deadline: "2025/04/30",
    tags: ["自動車", "EV", "カーボンニュートラル", "設備投資"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "105",
    name: "繊維・アパレル産業 高付加価値化支援補助金",
    ministry: "経産省",
    category: "技術開発",
    description: "国内繊維・アパレル産業の高付加価値化・ブランド力強化のための設備導入・海外展開を支援。上限500万円。",
    maxAmount: 500,
    adoptionRate: 47,
    deadline: "2025/05/31",
    tags: ["繊維", "アパレル", "ブランド", "高付加価値"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "106",
    name: "食品産業 スマート化支援補助金",
    ministry: "農水省",
    category: "デジタル化",
    description: "食品製造業・食品小売業のスマート化・省力化のためのロボット・AI・IoT導入を支援。上限3,000万円。",
    maxAmount: 3000,
    adoptionRate: 53,
    deadline: "2025/05/31",
    tags: ["食品", "スマート化", "ロボット", "省力化", "AI"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "107",
    name: "宿泊業 品質強化・安全対策補助金",
    ministry: "観光庁",
    category: "設備投資",
    description: "宿泊施設の品質向上・安全対策・バリアフリー化のための改修・設備導入を支援。上限500万円。",
    maxAmount: 500,
    adoptionRate: 64,
    deadline: "2025/08/31",
    tags: ["宿泊", "観光", "バリアフリー", "品質向上"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "108",
    name: "運輸業 EV・FCV導入補助金",
    ministry: "国交省",
    category: "省エネ",
    description: "トラック・バス等の電気自動車（EV）・燃料電池車（FCV）への転換を支援。車両購入費の一部を補助。",
    maxAmount: 2000,
    adoptionRate: 52,
    deadline: "2025/03/31",
    tags: ["運輸", "EV", "FCV", "脱炭素", "物流"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "109",
    name: "建設業 安全対策設備導入補助金",
    ministry: "国交省",
    category: "設備投資",
    description: "建設現場の安全管理向上のためのIoTセンサー・監視カメラ・転倒防止装置等の導入を支援。上限300万円。",
    maxAmount: 300,
    adoptionRate: 67,
    deadline: "2025/09/30",
    tags: ["建設業", "安全管理", "IoT", "設備"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "110",
    name: "小売業 キャッシュレス化推進補助金",
    ministry: "経産省",
    category: "デジタル化",
    description: "中小小売業・飲食業のキャッシュレス決済端末の導入費用を支援。QRコード・クレジット端末対応。上限100万円。",
    maxAmount: 100,
    adoptionRate: 72,
    deadline: "2025/03/31",
    tags: ["小売", "キャッシュレス", "QRコード", "決済"],
    isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
] as const;

export type MockGrant = (typeof MOCK_GRANTS)[number];

// 合計件数
export const MOCK_GRANTS_COUNT = MOCK_GRANTS.length;
